### ISSUE TITLE
gpu process time is too large

### ISSUE THREAD

**Issue by stoneeejianbing** [xmba15/generic_dbscan#2]
i run this code in my pc,and the result is the gpu process time is 500 ms and cpu 80 ms?
is any wrong i do?

**Comment by xmba15** [comment]
@stoneeejianbing 
Did you run the following build procedure?

```
make gpu_apps -j`nproc`
./build/examples/test_pointcloud_clustering_gpu ./data/street_no_ground.pcd 0.7 3
```
I rerun just now and on my machine it is still giving me 30 ms.

Which GPU are you using btw?

**Comment by stoneeejianbing** [comment]
my cuda version is 11.4
and the run result is this :
![image](https://user-images.githubusercontent.com/107661699/178240191-c4ac0def-7fbf-46a4-860e-e49b05551ca4.png)

number of points: 11619
number of clusters: 271
processing time (cpu): 76.2[ms]

number of points: 11619
number of clusters: 204
processing time (gpu): 1074.5[ms]

my pc nvidia smi : NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4

think you

**Comment by xmba15** [comment]
this is only the driver
```
NVIDIA-SMI 470.129.06 Driver 
```

Can you please tell me the hardware gpu you use? I was testing with a geforce titan x

**Comment by stoneeejianbing** [comment]
![电脑显卡性能](https://user-images.githubusercontent.com/107661699/178242857-f9874120-e30b-4b0d-bd0d-3a2056afdf1c.png)

**Comment by stoneeejianbing** [comment]
this is my pc ,and i also have a xavier,may be i can test code in the xavier?

**Comment by xmba15** [comment]
I think if you can, you should try this code with Jetson xavier.
The architecture of Jetson is different, so I am not sure if you can build the current code on Jetson though.

**Comment by xmba15** [comment]
if you are familiar with cuda programming, you can also try tweaking number of threads using here though

https://github.com/xmba15/generic_dbscan/blob/master/cuda/src/DBSCAN.cu#L154-L155

**Comment by xmba15** [comment]
@stoneeejianbing any update on xavier?

**Comment by stoneeejianbing** [comment]
yes,i have run the code on xavier,and i do not any change on the code.  This  take 300 ms time use gpu on xavier, and i run the code follow the read me. may be i must set something in the code ?

**Comment by stoneeejianbing** [comment]
yes,i have run the code on xavier,and i do not any change on the code.  This  take 300 ms time use gpu on xavier, and i run the code follow the read me. may be i must set something in the code ?

**Comment by xmba15** [comment]
@stoneeejianbing I do not have the hardware to test so I am afraid the above advice is all I can provide for now.

**Comment by stoneeejianbing** [comment]
still thank you very much
