### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by morte2025** [xmba15/generic_dbscan#5]
Thanks for your open source, After compiling the source code, I got the folloewing warning. Do you know how to avoid these warning?

<command-line>:0:16: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:19: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:23: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:16: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:19: warning: ISO C++11 requires whitespace after the macro name
<command-line>:0:23: warning: ISO C++11 requires whitespace after the macro name

warning: ‘void HandleError(cudaError_t, const char*, int)’ defined but not used [-Wunused-function]
 static void HandleError(cudaError_t err, const char* file, int line)
             ^~~~~~~~~~~

**Comment by xmba15** [comment]
@HMX2013 I addressed this issue in https://github.com/xmba15/generic_dbscan/pull/6
